version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data


  backend:
    image: anastasiaiziumskaya/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media


  frontend:
    env_file: .env
    image: anastasiaiziumskaya/kittygram_frontend
    command: cp -r /app/build/. /static/
    depends_on:
      - backend
    volumes:
      - static:/static

  gateway:
    image: anastasiaiziumskaya/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/static
      - media:/app/media
    ports:
      - 9000:80
